dachcom-digital/pimcore-members

- src/MembersBundle/EventListener/RestrictionStoreListener.php
Fixes incorrect type hinting at RestrictionStoreListener DataObjectEvents --> Model\DataObjectEvent. That caused pimcore to crash when adding/editing or deleting users.
> Fixed DataObjectEvents --> Model\DataObjectEvent for RestrictionStoreListener

- src/MembersBundle/Twig/Extension/NavigationExtension.php
In our current setup the navigation is not shown when the document is rendered as the 404 error page because the twig navigation extension throws an exception. When the page is accessed directly the navigation is rendered just fine.
This is caused by $this->tokenStorage->getToken() returning null instead of a token.
I have no idea why no token is available inside the 404 error handler.
> Avoid Exception when no token is available.

- src/MembersBundle/Controller/ResettingController.php
In the resetAction allow the token to be missing and check for isFrontendRequestByAdmin() to enable editing the page content.
> enable content editing of the password reset page

- src/MembersBundle/Validator/Constraints/PimcoreUniqueEntityValidator.php
The conditions in the PimcoreUniqueEntityValidator are currently initialized as a string, but then used as an array which throws an Exception.
Fixed by initializing as an empty array.
> Fix for Exception "[] operator not supported for strings"

- docs/300_CustomerDataFw.md
If members is being installed earlier ( e.g. before 5), install will fail.
> Clearify when to install members

- src/MembersBundle/Resources/public/js/backend/document/restriction.js
use either itemId or try to keep an instance of the object instead. Using ID could have some other side-effects
| New feature?  |no
| Deprecations? |no
> remove usage of id in extjs

- src/MembersBundle/Controller/RequestController.php
| Fixed tickets | no
Fix InvalidArgumentException when trying to download a file named "español.pdf"
> fix - the filename fallback must only contain ASCII characters

- src/MembersBundle/Resources/install/classes/class_MembersUser_export.json
| Fixed tickets | none
I suggest to update the default password hashing algorithm to something more secure than md5.
> fix default members password hashing algorithm

- src/MembersBundle/Adapter/User/UserTrait.php
| Deprecations? | yes
| Fixed tickets | #105
Added following helper functions:
`hasGroupId`, `hasGroupName`, `addGroup` and `removeGroup`.
For `hasGroupId` and `hasGroupName` I also used the `GroupInterface`. Would you instead prefer having `int $id` and `string $name`?
> [UserTrait] Helper functions

- src/MembersBundle/Manager/RestrictionManager.php
| Fixed tickets | #115
Change `} elseif ($element instanceof DataObject) {` 
to `} elseif ($element instanceof DataObject\Concrete) {` 
in functions `getElementRestrictedGroups(...)` and `getElementRestrictionStatus(...)` 
because Custom Objects extend  `Pimcore\Model\DataObject\Concrete`.
> [BUGFIX] [#115] Fix two conditions in class RestrictionManager

- src/MembersBundle/Document/Builder/BrickBuilder.php
After updating to Pimcore 6.3.3 (and more importantly Symfony 4.4) I got following error:
When moving from Symfony 4.3 to 4.4 we have to use the `TokenStorageInterface` instead of the class directly, as you can see here: https://github.com/symfony/symfony/commit/20df3a125cfb56794ada342ddf96023b91854a9c#diff-c437482da579aadf3e37c903af62fccdR24-R34
> fix: inject the token storage interface instead of the class

- src/MembersBundle/Manager/UserManager.php
only set the initial groups if initial groups are present in the config. this prevents the groups field from being emptied when setting the groups-field via for example a form.
> only set Initial Groups if present

- src/MembersBundle/EventListener/ForbiddenRouteListener.php
[This line](https://github.com/dachcom-digital/pimcore-members/blob/master/src/MembersBundle/EventListener/ForbiddenRouteListener.php#L83) is checking if route names contain `document_` anywhere in them. In one project I had the route `app_order_document_preview `, which of course didn't contain a `contentDocument` key in the request. Because of that the restriction status check failed with the error:
```log
Argument 1 passed to MembersBundle\Manager\RestrictionManager::getElementRestrictionStatus() must be an instance of Pimcore\Model\AbstractModel, null given
```
With this PR the check explicitly checks if the string begins with …
> fix: falsely checking routes without contentDocument

- UPGRADE.md
- docs/40_Events.md
- src/MembersBundle/Controller/Admin/RestrictionController.php
- src/MembersBundle/Event/RestrictionEvent.php
- src/MembersBundle/EventListener/RestrictionStoreListener.php
- src/MembersBundle/MembersEvents.php
- src/MembersBundle/Resources/config/pimcore/routing.yml
- src/MembersBundle/Resources/public/js/backend/document/restriction.js
- src/MembersBundle/Resources/public/js/backend/startup.js
- src/MembersBundle/Service/RestrictionService.php
- tests/_support/Helper/Members.php
- tests/functional/Restriction/AssetRestrictionCest.php
- tests/functional/Restriction/DocumentRestrictionCest.php
- tests/functional/Restriction/ObjectRestrictionCest.php
| Branch?       | dev-master 
| Deprecations? | /no
| Fixed tickets | #148
This PR introduces 3 new Events:
- `ENTITY_CREATE_RESTRICTION`
- `ENTITY_UPDATE_RESTRICTION`
- `ENTITY_DELETE_RESTRICTION`
I also improved the `POST_UPDATE` move event: If you change the `$entity->setParent()` via API, the restriction service will automatically check/update for oudated/updated restrictions!
> improve restriction event handling, resolves #148

- UPGRADE.md
- docs/210_RestrictedNavigation.md
- src/MembersBundle/Twig/Extension/NavigationExtension.php
- tests/_etc/config.yml
- tests/_etc/config/app/controller/DefaultController.php
- tests/_etc/config/app/views/navigation.html.twig
- tests/_support/Helper/Members.php
- tests/functional/Frontend/Navigation/RestrictedNavigationCest.php
Navigation was still using the deprecated buildNavigation method.
In addition, it was impossible to configure custom parameters, which is
possible when you use the Pimcore build_nav Twig function.
The logic was refactored to work similar to the Pimcore build_nav. The old
deprecated setup still works, but parameters can (and should) be used now.
In addition, when configuring the pageCallback parameter, it is now called
within the members callback, which also forwards the restriction element,
allowing you to override the restriction settings and apply other logic.
| Deprecations? | yes (in Pimcore)
> refactor: update Twig navigation to allow parameters

- UPGRADE.md
- src/MembersBundle/Resources/config/pimcore/config.yml
| Branch?       | 2.5
| Fixed tickets | -
Problem: Documents with an url like '/administration' weren't redirected to the login page
Caused by: All uri's starting with '/admin' were excluded from the firewall
Resolved by: Only ignoring '/admin' itself and '/admin/.*'
> fix: protect documents starting with admin

- src/MembersBundle/Controller/AuthController.php
- src/MembersBundle/Controller/ChangePasswordController.php
- src/MembersBundle/Controller/DeleteAccountController.php
- src/MembersBundle/Controller/OAuthController.php
- src/MembersBundle/Controller/ProfileController.php
- src/MembersBundle/Controller/RegistrationController.php
- src/MembersBundle/Controller/ResettingController.php
- src/MembersBundle/Document/Areabrick/MembersLogin/MembersLogin.php
Since Symfony 5.3 there is a new [form handler helper](https://symfony.com/blog/new-in-symfony-5-3-form-handler-helper), which returns the proper HTTP response codes for form submissions. This is especially useful when using libraries like Symfony UX Turbo, as they rely on those in order to reload/redirect the pages correctly.
LMK if anything else needs to be done.
Thanks in advance!
> fix: return proper HTTP response codes on form submit

- src/MembersBundle/Security/RestrictionQuery.php
There are basically two things to fix:
- Wrong query (syntax)
- Wrong join behaviour
i. The `$queryIdentifier` was set wrong in the Toolbox Bundle (`assets.id` instead of `id`). Therefore the resulting query contained `assets.assets.id` which is a non-existing field.
ii. `$query->where()` and `$query->groupBy()` overrides the conditions/groups which are being applied by Pimcore in the Listing which leads to a parameter mismatch. Using `andWhere()` and `addGroupBy()` fixes that.
Using `$query->join()` performs an inner join which means that only assets, etc. **with some restrictions defined** appear in the result set. All without any …
> Fix the RestrictionQuery to prevent empty results/wrong query

- src/MembersBundle/EventListener/ForbiddenRouteListener.php
Currently the ForbiddenRouteListener sets the full uri as _target_path, which seems to be ignored by the firewall, since i always get redirected to / after a successful login. If i use getPathInfo it works as expected.
> remove scheme and host from _target_path

- UPGRADE.md
- src/MembersBundle/Controller/RequestController.php
| Branch?       | 3.x
| Fixed tickets | #172
This PR removes the `PIMCORE_ASSET_DIRECTORY` prefix, if the file is served from an S3 bucket. Therefore it will be possible to use assets stored on S3 to be downloaded via the protected asset downloader.
> [Protected Asset Downloader] Allow S3 assets to be protected

- UPGRADE.md
- docs/240_AssetProtection.md
- src/MembersBundle/Controller/RequestController.php
>  use flysystem stream in file request

- UPGRADE.md
- docs/SSO/20_Installation.md
- src/MembersBundle/DependencyInjection/MembersExtension.php
- src/MembersBundle/Resources/config/packages/security_auth_manager.yaml
- src/MembersBundle/Resources/config/services/event.yml
> configurable firewall name via container parameter

- .github/workflows/codeception.yml
- UPGRADE.md
- config/packages/security_auth_manager.yaml
- config/services/event.yaml
- docs/40_Events.md
- docs/SSO/12_ResourceMapping.md
- docs/SSO/20_Installation.md
- src/DependencyInjection/MembersExtension.php
- src/Event/OAuth/OAuthResourceRefreshEvent.php
- src/Exception/EntityNotRefreshedException.php
- src/MembersEvents.php
- src/Security/Authenticator/OAuthIdentityAuthenticator.php
- src/Security/OAuth/AccountConnector.php
- src/Security/OAuth/AccountConnectorInterface.php
- src/Security/OAuth/OAuthRegistrationHandler.php
- src/Service/ResourceMappingService.php
- tests/_envs/github.yml
- tests/_etc/config/app/config.yaml
- tests/_etc/config/app/system_settings.yaml
> add OAUTH_RESOURCE_MAPPING_REFRESH event, add members.firewall_name parameter

- .github/workflows/codeception.yml
- .github/workflows/ecs.yml
- .github/workflows/php-stan.yml
- src/CoreExtension/Provider/RoleOptionsProvider.php
| Fixed tickets | fixes #201 
See #201
> #201 Optimize RoleOptionsProvider to respect the default role.

- README.md
- UPGRADE.md
- config/install/translations/frontend.csv
- config/pimcore/routing/registration.yaml
- docs/60_RegistrationTypes.md
- src/Controller/RegistrationController.php
- src/DependencyInjection/Configuration.php
- src/Mailer/Mailer.php
- templates/registration/confirm_preview.html.twig
- tests/Unit/Config/ConfigurationTest.php
- tests/Unit/Dao/GroupTest.php
- tests/Unit/Dao/SsoIdentityTest.php
- tests/Unit/Dao/UserTest.php
- tests/Unit/Manager/ClassManagerTest.php
- tests/Unit/Manager/LoginManagerTest.php
- tests/Unit/Manager/RestrictionManagerTest.php
- tests/Unit/Manager/SsoIdentityManagerTest.php
- tests/Unit/Manager/UserManagerTest.php
- tests/Unit/Security/RoleOptionsProviderTest.php
- tests/Unit/Security/UserCheckerTest.php
- tests/Unit/Security/UserProviderTest.php
Related: https://github.com/dachcom-digital/pimcore-members/issues/175, @aarongerig We finally came up with a proper solution...
Some email providers have spam detection or security features that prefetch URLs from incoming emails (e.g., Safe Links in Microsoft Defender for Office 365).
To prevent unintended automatic activations, you can enable a "preview confirmation" page.
This requires users to manually confirm their registration by clicking an additional button.
This feature is disabled by default. To enable it, update your configuration as follows:
```yaml
members:
enable_preview_confirmation: true # default is …
```
> add preview confirmation workflow

- src/Controller/RequestController.php
| Bug fix?      | kind of?
| New feature?  |no
Restricted assets are served by the `RequestController.php` and not directly as a file path. With video assets this results in strange behaviour for chrome, safari and firefox video player. The players scrubber/progress bar cannot be dragged to a specific point in the video. It always jumps back to the current time in the video and flickers.
Here an example in Chromes HTML 5 videolayer:
https://github.com/user-attachments/assets/67182b02-a350-4c2e-ba50-ac780d92800a
> change serving of protected video assets

- src/Controller/RequestController.php
The drop-in replacement works just fine – tested it with one of our projects. 👍
> [Restriction] Use AssetService to stream response by URI
