docs/20_CustomClassName.md
=> Documentation fix

src/MembersBundle/Document/Areabrick/MembersLogin/MembersLogin.php
| New feature?  |no
| Deprecations? |no
=> fix redirect in brick after successfull login

UPGRADE.md, src/MembersBundle/Adapter/User/UserTrait.php, src/MembersBundle/Resources/config/validation/User.yml, tests/bundle_tests/functional/Validation/GetterCest.php
| Bug fix?      | yes/no
| New feature?  | yes/no
| Deprecations? | yes/no
| Fixed tickets | #76
=> map entity validation to user interface

.travis.yml, README.md, src/MembersBundle/CoreExtension/GroupMultiselect.php, src/MembersBundle/CoreExtension/Provider/RoleOptionsProvider.php, src/MembersBundle/Migrations/Version20190508092938.php, src/MembersBundle/Resources/config/services/options_provider.yml, src/MembersBundle/Resources/install/classes/class_MembersGroup_export.json, src/MembersBundle/Tool/Install.php, src/MembersBundle/Tool/VersionHelper.php, tests/_etc/config/system/config.yml, tests/_support/Helper/PimcoreBackend.php, tests/_support/Test/DachcomBundleTestCase.php, tests/_support/Util/MembersHelper.php, tests/rest/ObjectTest.php, tests/unit/Dao/GroupTest.php, tests/unit/Dao/UserTest.php, tests/unit/Security/RoleOptionsProviderTest.php
| Fixed tickets | #95
Also:
- Migrate OptionsResolver for `Roles` to a real symfony service
- Add some additional DAO Tests
=> Fix Group MultiSelect Relation Fetch

src/MembersBundle/Controller/RequestController.php
| Deprecations? | yes
| Fixed tickets | #94
=> do not use formatted file size in content-length header, see #94

tests/_etc/travis/install
=> improve travis composer installation

src/MembersBundle/Security/RestrictionQuery.php, tests/_etc/travis/install
| Bug fix?      | sort of
| BC breaks?    | yes
| Fixed tickets | #118
=> Harmonize Restriction Query

.travis.yml, README.md, UPGRADE.md, src/MembersBundle/CoreExtension/GroupMultiselect.php, src/MembersBundle/Document/Builder/BrickBuilder.php, tests/_bootstrap.php, tests/_etc/config/bundle/system.yml.template, tests/acceptance.suite.disabled.yml, tests/functional.suite.dist.yml, tests/rest.suite.dist.yml, tests/rest/ObjectTest.php, tests/unit.suite.dist.yml
=> pimcore 6.5 compatibility

docs/SSO/10_Overview.md, docs/SSO/31_Listener.md, src/MembersBundle/DependencyInjection/Configuration.php, src/MembersBundle/DependencyInjection/MembersExtension.php, src/MembersBundle/EventListener/Maintenance/SsoCleanUpExpiredTokenListener.php, src/MembersBundle/Manager/SsoIdentityManager.php, src/MembersBundle/Manager/SsoIdentityManagerInterface.php, src/MembersBundle/Resources/config/services/oauth/mainentance.yml, src/MembersBundle/Security/OAuth/OAuthRegistrationHandler.php
=> add token expire clean up

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml, README.md, UPGRADE.md, docs/20_ClassCustomization.md, docs/SSO/20_Installation.md, src/MembersBundle/DependencyInjection/Configuration.php, src/MembersBundle/Manager/UserManager.php
=> Feature custom object keys

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml
Fixed tests to pull from correct branch.
=> Fixed tests branches

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml, UPGRADE.md, src/MembersBundle/Controller/Admin/RestrictionController.php
| New feature?  |no
| Fixed tickets |  #162
=> fix inherited group check

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml, composer.json, src/MembersBundle/Command/ClassInstallerCommand.php, src/MembersBundle/Command/OAuthSetupCommand.php, src/MembersBundle/Service/RestrictionService.php, src/MembersBundle/Twig/Extension/NavigationExtension.php, tests/_etc/config/app/config.yml, tests/_support/Helper/Members.php
=> adjust tests

UPGRADE.md, docs/200_Restrictions.md, phpstan.neon, src/MembersBundle/Controller/RequestController.php, src/MembersBundle/DependencyInjection/Configuration.php, src/MembersBundle/EventListener/AssetFrontendPathListener.php, src/MembersBundle/EventListener/TreeListener.php, src/MembersBundle/Manager/RestrictionManager.php, src/MembersBundle/Manager/RestrictionManagerInterface.php, src/MembersBundle/Resources/config/pimcore/routing.yml, src/MembersBundle/Resources/config/services/event.yml, src/MembersBundle/Security/RestrictionQuery.php, src/MembersBundle/Security/RestrictionUri.php, tests/_support/Helper/Members.php
=> add public asset path protection

README.md, composer.json, src/MembersBundle/Resources/public/js/backend/startup.js
=> move to pimcore native js events

src/MembersBundle/Controller/RequestController.php, src/MembersBundle/EventListener/AssetFrontendPathListener.php, src/MembersBundle/Resources/config/pimcore/routing.yml, src/MembersBundle/Security/RestrictionUri.php
| Bug fix?      |  no
This is a regression of #177.
=> improve public asset url handling

README.md, UPGRADE.md, docs/SSO/20_Installation.md, src/MembersBundle/DependencyInjection/MembersExtension.php, src/MembersBundle/Resources/config/packages/security_auth_manager.yaml, src/MembersBundle/Resources/config/packages/security_legacy.yaml, src/MembersBundle/Resources/config/pimcore/config.yml, src/MembersBundle/Resources/config/security_authenticator_manager.yml, src/MembersBundle/Resources/config/security_legacy.yml, src/MembersBundle/Resources/config/services/oauth/security.yml, src/MembersBundle/Resources/config/services/security.yml, src/MembersBundle/Security/Authenticator/OAuthIdentityAuthenticator.php, src/MembersBundle/Security/Encoder/Factory/UserAwareEncoderFactory.php, src/MembersBundle/Security/OAuthIdentityAuthenticator.php
| Bug fix?      | /no
| Fixed tickets | #160
=> use new authenticator manager

UPGRADE.md, src/MembersBundle/Controller/RequestController.php
=> respect original asset paths in protected env

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml
=> Pimcore 10.6 release

.github/workflows/codeception.yml, .github/workflows/ecs.yml, .github/workflows/php-stan.yml, UPGRADE.md, docs/40_Events.md, docs/SSO/12_ResourceMapping.md, src/MembersBundle/Event/OAuth/OAuthResourceRefreshEvent.php, src/MembersBundle/Exception/EntityNotRefreshedException.php, src/MembersBundle/MembersEvents.php, src/MembersBundle/Security/Authenticator/OAuthIdentityAuthenticator.php, src/MembersBundle/Security/OAuth/AccountConnector.php, src/MembersBundle/Security/OAuth/OAuthRegistrationHandler.php, src/MembersBundle/Service/ResourceMappingService.php
=> add oauth refresh event

src/Adapter/User/UserTrait.php
| Fixed tickets | https://github.com/dachcom-digital/pimcore-members/issues/199
=> Fix bug when you have an empty roles.

UPGRADE.md, src/Manager/UserManager.php
=> do not initialize memberStorageId in UserManager::constructor
